
volumes:
  cassandra:
  pulsar-conf:
  pulsar-data:
  etcd:
  minio-data:
  milvus:

services:

  cassandra:
    image: docker.io/cassandra:4.1.5
    ports:
      - "9042:9042"
    volumes:
      - "cassandra:/var/lib/cassandra"
    restart: on-failure:100

  pulsar:
    image: docker.io/apachepulsar/pulsar:3.3.0
    command: bin/pulsar standalone
    ports:
      - "6650:6650"
      - "8080:8080"
    volumes:
      - "pulsar-conf:/pulsar/conf"
      - "pulsar-data:/pulsar/data"
    restart: on-failure:100

  pulsar-manager:
    image: docker.io/apachepulsar/pulsar-manager:v0.3.0
    ports:
      - "9527:9527"
      - "7750:7750"
    environment:
      SPRING_CONFIGURATION_FILE: /pulsar-manager/pulsar-manager/application.properties
    restart: on-failure:100

  etcd:
    image: quay.io/coreos/etcd:v3.5.5
    command:
      - "etcd"
      - "-advertise-client-urls=http://127.0.0.1:2379"
      - "-listen-client-urls"
      - "http://0.0.0.0:2379"
      - "--data-dir"
      - "/etcd"
    environment:
      ETCD_AUTO_COMPACTION_MODE: revision
      ETCD_AUTO_COMPACTION_RETENTION: "1000"
      ETCD_QUOTA_BACKEND_BYTES: "4294967296"
      ETCD_SNAPSHOT_COUNT: "50000"
    ports:
      - "2379:2379"
    volumes:
      - "etcd:/etcd"
    restart: on-failure:100
    
  minio:
    image: docker.io/minio/minio:RELEASE.2024-07-04T14-25-45Z
    command:
      - "minio"
      - "server"
      - "/minio_data"
      - "--console-address"
      - ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9001:9001"
    volumes:
      - "minio-data:/minio_data"
    restart: on-failure:100

  milvus:
    image: docker.io/milvusdb/milvus:v2.4.5
    command:
      - "milvus"
      - "run"
      - "standalone"
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    ports:
      - "9091:9091"
      - "19530:19530"
    volumes:
      - "milvus:/var/lib/milvus"
    restart: on-failure:100

